### ISSUE TITLE
Is the inclusion of non-timezone information files intentional?

### ISSUE THREAD

**Issue by mbargull** [python/tzdata#28]
This package includes the files
```
zoneinfo/leapseconds
zoneinfo/iso3166.tab
zoneinfo/zone1970.tab
zoneinfo/zone.tab
zoneinfo/tzdata.zi
```
. Is this intentional?
Due to lack of knowledge, I can't say if it makes sense to include them or not.
I just noticed them when comparing the list of files to what the `install_data` `Makefile` target outputs.

If their inclusion is unintentional, you could simplify your `make` call with the `install_data` target to
```sh
make \
  TOPDIR="${path_to_tzdata_package}" \
  USRSHAREDIR= \
  POSIXRULES= \
  ZFLAGS='-b slim' \
  install_data
```
(By setting `USRSHAREDIR` to an empty value and `TOPDIR` to the directory that will hold the `zoneinfo` folder, you can also avoid the post-build `shutil.move` you currently do.)

**Comment by pganssle** [comment]
This is (mostly) not non-timezone data.

`tzdata.zi` is an un-compiled minified version of the entire database, and contains more information than the compiled verison.  The `leapseconds` file is the distribution of leap second timings, and the tab files have metadata about time zones in them. This project should aim to provide what a standard installation of `tzdata` would give you on your system, which includes these files.

**Comment by mbargull** [comment]
Thank you for the insights and confirmation!
