### ISSUE TITLE
Issues with the renaming of Kyiv timezone

### ISSUE THREAD

**Issue by franciscoatsantos** [python/tzdata#56]
After upgrading to version 2022.2.1 with pip, my django instance returned `ZoneInfoNotFound`.
I then confirmed that after upgrading the version, the name on the zoneinfo folder remains 'Kiev'.

**Comment by pganssle** [comment]
There is no version `2022.2.1`, so I am not sure exactly is happening here. Generally speaking `zoneinfo` will first search common system paths before falling back to `tzdata`, but the latest `tzdata` should have `Europe/Kyiv`, so if you've installed `tzdata` you should be seeing it.

Try updating your system, and if it still doesn't work maybe just fall back to using `Europe/Kiev`, which exists in older versions and also will continue to exist in future versions.
