### ISSUE TITLE
ZoneInfo('America/Mexico_City') subtracts one hour less from UTC

### ISSUE THREAD

**Issue by tribumirkov** [python/tzdata#68]
Hey folks,

Mexico decided not to move any more to summer time from 2023 onwards:

https://www.marca.com/mx/actualidad/2023/03/28/6423471a46163f89688b45c3.html

So when I apply ZoneInfo to a datetime object containing UTC time, I get the local time of Mexico City which is one hour "faster".

To reproduce the error:

from zoneinfo import ZoneInfo
from datetime import datetime

utc = datetime.utcnow()
mexican_zone = ZoneInfo('America/Mexico_City')
local = utc.replace(tzinfo=timezone.utc).astimezone(mexican_zone)
print(local)

Please advise!

**Comment by pganssle** [comment]
The Python version of `tzdata` is already the latest version to be released. `zoneinfo` pulls data first from your operating system if it exists, then from this package if it's installed. You likely need to update your operating system time zone data, or your operating system needs to update their tzdata package.
