### ISSUE TITLE
Add `tzdata` to `python` PyPI organisation?

### ISSUE THREAD

**Issue by hugovk** [python/tzdata#84]
Following https://discuss.python.org/t/request-python-organisation-on-pypi/26545, we now have two organisations on PyPI: https://pypi.org/org/cpython/ and https://pypi.org/org/python/

We can add the `tzdata` PyPI project to one of them.

The main benefits are:

* Visibility: we'll be able to see our packages under a PyPI org page

* Maintainability: we can share granular PyPI access to improve the bus factor

The [SC's categorisation](https://discuss.python.org/t/request-python-organisation-on-pypi/26545/5) for them suggests `tzdata` would be suitable for the `python` org:

> * `cpython`: for development tools that are tied fairly closely to CPython development. This could for example include blurb and cherry-picker. Users generally shouldn’t have to care except for developing CPython itself (although that doesn’t mean the tools necessarily have to be unusable for anyone else).
> * `python`: for general-audience projects that are maintained the Python Core Devs. An example for this category would be tzdata.

@pganssle @abalkin How does this sound?

If you'd like to go ahead, please could you add me (I'm `hugovk` there too) as "owner" at https://pypi.org/project/tzdata/ and I'll add it.

**Comment by pganssle** [comment]
Sounds good to me, thanks Hugo!

**Comment by hugovk** [comment]
And now added, thanks!

* https://pypi.org/org/python/
* https://pypi.org/project/tzdata/
